language: go
sudo: required

install:
- go get -v github.com/spf13/hugo

script: bash ./scripts/cibuild

branches:
  only:
  - master

deploy:
  local_dir: public
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
