language: ruby
rvm:
 - 2.2

script: ./scripts/cibuild

# branch whitelist, only for GitHub Pages
#branches:
#  only:
#   - gh-pages   # test the gh-pages branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true  # speeds up installation of html-proffer
