language: go
sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install python3-pygments

install:
- go get -v github.com/spf13/hugo

script: hugo

branches:
  only:
  - master

deploy:
  local_dir: public
  provider: pages
  skip_cleanup: true
  fqdn: $BASE_URL
  github_token: $GH_TOKEN
  on:
    branch: master
