language: ruby
rvm:
 - 2.2

script: ./scripts/cibuild

cache: bundler

# branch whitelist
branches:
  only:
  - master     # test the master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  - JEKYLL_ENV=production

deploy:
  skip_cleanup: true
  provider: script
  script: scripts/gh-pages-deploy.sh
  on:
    branch: master