# --------------------------------------------------
# Site settings
# --------------------------------------------------
title: jimueller
email: blog[at]jimueller.com
tagline: "Magnets, Milksteak, and Rum Ham"
description: "Developer. Covering topics on Web Development, Scripting, fitness, and funny."
baseurl: ""
url: "http://jimueller.com"
#url: "http://localhost:4000"
paginate: 5

# --------------------------------------------------
# Accounts
# --------------------------------------------------
usernames:
  default: jimueller
  twitter: jimueller
  github:  jimueller
  bitbucket: jrmdev
  
  
# --------------------------------------------------
# Page / Post Defaults
# --------------------------------------------------
defaults:
 -
   scope:
     type: "posts"
   values:
     layout: "post"
     author: "Jim Mueller"

excerpt_separator: <!--more-->

# --------------------------------------------------
# Build Settings
# --------------------------------------------------
timezone: America/Chicago
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
encoding: utf-8
exclude:  ["vendor", "scripts", ".bak", "README.md", "Gemfile", "_deploy.yml", "wercker.yml", "Guardfile"]
gems: [octopress, jekyll-paginate]

# --------------------------------------------------
# Output Settings
# --------------------------------------------------
permalink: pretty
paginate_path: /page/:num
post_ext: md
page_ext: html

# Style
sass:
  style: :expanded

# --------------------------------------------------
# Plugins
# --------------------------------------------------

## Live Tiles
ie_tile_color: #003EFF
ie_tile_small: images/livetile/tiny.png
ie_tile_medium: images/livetile/square.png
ie_tile_wide: images/livetile/wide.png
ie_tile_large: images/livetile/large.png
