verson: 2.1

orbs:
  hugo: circleci/hugo@0.3.1

workflows:
  main:
    jobs:
      - hugo/build:
          version: '0.55'
      - deploy:
          requires:
            - hugo/build
          filters:
            branches:
              only: master

jobs:
  deploy: